// eslint-disable-next-line import/no-anonymous-default-export
export default [{"label":"연료펌프컨트롤모듈(FPCM)","value":5},
{"label":"과급압컨트롤솔레노이드","value":5},
{"label":"과급압력센서","value":5},
{"label":"슈퍼차져","value":5},
{"label":"터보과급기","value":5},
{"label":"터보임펠라","value":5},
{"label":"과급기","value":5},
{"label":"터빈","value":5},
{"label":"터보오일파이프","value":2},
{"label":"터보","value":5},
{"label":"LPG 솔레노이드","value":5},
{"label":"터보차저","value":5},
{"label":"게이트밸브","value":5},
{"label":"웨이스트게이트밸브","value":5},
{"label":"레조네이터","value":2},
{"label":"인테이크파이프","value":2},
{"label":"엔진냉각장치","value":5},
{"label":"엔진관련센서","value":5},
{"label":"엔진찜빠","value":3},
{"label":"엔진찐빠","value":3},
{"label":"엔진부조","value":3},
{"label":"연료리턴파이프","value":2},
{"label":"타이밍체인 텐셔너 암","value":4},
{"label":"타이밍체인 텐셔너","value":4},
{"label":"연료리턴호스","value":2},
{"label":"VVT커버","value":2},
{"label":"VVT컨트롤러","value":5},
{"label":"CVVT컨트롤러","value":5},
{"label":"VVT커버누유","value":2},
{"label":"CVVT커버 ","value":2},
{"label":"CVVT커버누유","value":2},
{"label":"터보챠저","value":5},
{"label":"인터쿨러호스","value":2},
{"label":"인터쿨러파이프","value":2},
{"label":"인터쿨러호수","value":2},
{"label":"진공호스","value":2},
{"label":"라바호수","value":2},
{"label":"라바호스","value":2},
{"label":"진공호수","value":2},
{"label":"밸브간극조정","value":2},
{"label":"인터쿨러","value":5},
{"label":"연료펌프모듈","value":5},
{"label":"연료휠터센서","value":5},
{"label":"연료여과기센서","value":5},
{"label":"퓨얼필터센서","value":5},
{"label":"퓨얼휠터센서","value":5},
{"label":"fuel filter sensor","value":5},
{"label":"연료필터 센서","value":5},
{"label":"연료휠터","value":2},
{"label":"연료여과기","value":2},
{"label":"퓨얼필터","value":2},
{"label":"퓨얼휠터","value":2},
{"label":"fuel filter","value":2},
{"label":"연료필터","value":2},
{"label":"연료히터릴레이","value":5},
{"label":"오일온도센서(OTS)","value":5},
{"label":"컨트롤 랙 센서(CRS)","value":5},
{"label":"오일씰(엔진)","value":2},
{"label":"엔진와이어링배선","value":5},
{"label":"엔진배선","value":5},
{"label":"메인하네스","value":5},
{"label":"라지에다 펜","value":5},
{"label":"코어플러그","value":4},
{"label":"익스텐션플러그","value":4},
{"label":"엔진실린더물뽕","value":4},
{"label":"엔진블럭물뽕","value":4},
{"label":"엔진실린더물봉","value":4},
{"label":"엔진블럭물봉","value":4},
{"label":"펜클러치","value":5},
{"label":"나제다펜","value":5},
{"label":"세루모터","value":6},
{"label":"세루모더","value":6},
{"label":"세루모타","value":6},
{"label":"세루","value":6},
{"label":"세루모다","value":6},
{"label":"쎄루모터","value":6},
{"label":"쎄루모더","value":6},
{"label":"쎄루모타","value":6},
{"label":"쎄루","value":6},
{"label":"쎄루모다","value":6},
{"label":"오일실","value":2},
{"label":"라지에이터펜","value":5},
{"label":"라디에이터펜","value":5},
{"label":"쿨링펜","value":5},
{"label":"전자식 섬머스타트","value":5},
{"label":"전자식 섬머스텟","value":5},
{"label":"전자식 섬머스탯","value":5},
{"label":"전자식 썸모스타트","value":5},
{"label":"전자식 썸모스텟","value":5},
{"label":"전자식 썸머스타트","value":5},
{"label":"전자식 썸머스탯","value":5},
{"label":"전자식 썸모스탯","value":5},
{"label":"전자식 서머스탯","value":5},
{"label":"전자식 썸머스텟","value":5},
{"label":"섬머스타트","value":5},
{"label":"흡기포트","value":4},
{"label":"배기포트","value":4},
{"label":"서머스탯","value":5},
{"label":"섬머스텟","value":5},
{"label":"섬머스탯","value":5},
{"label":"썸모스타트","value":5},
{"label":"썸모스텟","value":5},
{"label":"썸머스타트","value":5},
{"label":"썸머스탯","value":5},
{"label":"썸모스탯","value":5},
{"label":"썸머스텟","value":5},
{"label":"냉각펜","value":5},
{"label":"스로틀포지션센서(TPS)","value":5},
{"label":"트로틀포지션센서(TPS)","value":5},
{"label":"트로틀바디","value":5},
{"label":"트로틀밸브","value":5},
{"label":"스로틀밸브","value":5},
{"label":"스로틀바디","value":5},
{"label":"트로틀드럼","value":5},
{"label":"스로틀드럼","value":5},
{"label":"전자식 서모스타트","value":5},
{"label":"전자식 서모스텟","value":5},
{"label":"전자식 서모스탯","value":5},
{"label":"전자식 써모스타트","value":5},
{"label":"전자식 써모스텟","value":5},
{"label":"서모스타트","value":5},
{"label":"서모스텟","value":5},
{"label":"서모스탯","value":5},
{"label":"리턴스프링","value":5},
{"label":"써모스타트","value":5},
{"label":"써모스텟","value":5},
{"label":"사일런트 체인","value":4},
{"label":"사일런트 샤프트","value":4},
{"label":"스로틀챔버","value":5},
{"label":"트로틀챔버","value":5},
{"label":"엔진후앙","value":5},
{"label":"오일쿨러(엔진)","value":5},
{"label":"오일쿨러호스","value":2},
{"label":"상부오일팬","value":4},
{"label":"하부오일팬","value":4},
{"label":"오일팬(엔진)","value":4},
{"label":"오일팬누유(엔진)","value":2},
{"label":"삼원촉매 컨버터","value":2},
{"label":"삼원촉매","value":2},
{"label":"촉매변환기","value":2},
{"label":"촉매 컨버터","value":2},
{"label":"산화촉매","value":2},
{"label":"봄베","value":5},
{"label":"봄베가스","value":5},
{"label":"오일펌프(엔진)","value":4},
{"label":"에어크리너박스","value":2},
{"label":"에어통(엔진)","value":2},
{"label":"에어크리너통","value":2},
{"label":"오일 프레셔 스위치","value":5},
{"label":"오일압력스위치","value":5},
{"label":"oil filter(엔진)","value":2},
{"label":"오일필터(엔진)","value":2},
{"label":"요소수","value":2},
{"label":"요소수라인","value":2},
{"label":"요소수탱크","value":2},
{"label":"EGR 컨트롤밸브","value":5},
{"label":"점화스위치","value":5},
{"label":"진공펌프","value":5},
{"label":"2차공기펌프","value":5},
{"label":"촉매","value":2},
{"label":"캠샤프트","value":4},
{"label":"캠풀리","value":4},
{"label":"캠스프라켓","value":4},
{"label":"캠스프로켓","value":4},
{"label":"캠축","value":4},
{"label":"커먼레일","value":5},
{"label":"라지에다 팬","value":5},
{"label":"나제다 팬","value":5},
{"label":"나제다 휀","value":5},
{"label":"나제다 후앙","value":5},
{"label":"라지에이터 코어","value":5},
{"label":"라디에다 코어","value":5},
{"label":"라지에다 코어","value":5},
{"label":"라디에이터 코어","value":5},
{"label":"라지에이터 캡","value":2},
{"label":"라디에다 캡","value":2},
{"label":"라지에다 캡","value":2},
{"label":"라디에이터 캡","value":2},
{"label":"라지에이터 휀","value":5},
{"label":"라지에이터 팬","value":5},
{"label":"라지에이터 후앙","value":5},
{"label":"라지에다 휀","value":5},
{"label":"라디에이터 휀","value":5},
{"label":"라디에이터후앙","value":5},
{"label":"라디에이터 팬","value":5},
{"label":"미터링밸브","value":5},
{"label":"타이밍체인 오일젯","value":4},
{"label":"가압밸브","value":4},
{"label":"오일갤러리","value":4},
{"label":"부압밸브","value":4},
{"label":"반달키","value":4},
{"label":"워터재킷","value":4},
{"label":"워터자켓","value":4},
{"label":"워터 아웃렛 호스","value":2},
{"label":"워터 인렛 호스","value":2},
{"label":"전해액","value":2},
{"label":"인디게이터(연료)","value":2},
{"label":"하부호스","value":2},
{"label":"상부호스","value":2},
{"label":"리저버 호스","value":2},
{"label":"리저버 탱크","value":2},
{"label":"전자식워터펌프(엔진)","value":5},
{"label":"워터호스","value":2},
{"label":"라디에이터 하부 마운팅 인슐레이터","value":2},
{"label":"라디에이터 하부 마운팅","value":2},
{"label":"인렛미터링밸브","value":5},
{"label":"냉각휀","value":5},
{"label":"에어플로어센서","value":5},
{"label":"에어플로워센서","value":5},
{"label":"연료히터","value":5},
{"label":"전동팬","value":5},
{"label":"전동펜","value":5},
{"label":"전동휀","value":5},
{"label":"후앙","value":5},
{"label":"쿨링팬","value":5},
{"label":"냉각팬","value":5},
{"label":"이그니션코일","value":2},
{"label":"크랭크 축","value":4},
{"label":"크랭크 샤프트","value":4},
{"label":"크랭크 샤프트 베어링","value":4},
{"label":"크랭크 샤프트 댐퍼풀리","value":4},
{"label":"크랭크 샤프트 포지션센서","value":5},
{"label":"타이밍체인 가이드","value":4},
{"label":"체인가이드","value":4},
{"label":"타이밍체인 스프라켓","value":4},
{"label":"타이밍체인 스프로켓","value":4},
{"label":"타이밍체인","value":4},
{"label":"타이밍체인카바누유","value":2},
{"label":"타이밍체인카바 ","value":4},
{"label":"타이밍체인커버누유","value":2},
{"label":"타이밍체인커버","value":4},
{"label":"소메달","value":4},
{"label":"대메달","value":4},
{"label":"곤로드","value":4},
{"label":"컨롯드","value":4},
{"label":"컨로드","value":4},
{"label":"곤롯드","value":4},
{"label":"커넥팅로드 메달","value":4},
{"label":"커넥팅로드 메탈베어링","value":4},
{"label":"커넥팅로드 베어링","value":4},
{"label":"커넥팅로드","value":4},
{"label":"흡기매니폴드 개스킷","value":2},
{"label":"흡기매니홀드 개스킷","value":2},
{"label":"흡기매니폴드 가스켓","value":2},
{"label":"흡기매니홀드 가스켓","value":2},
{"label":"흡기매니폴드","value":5},
{"label":"흡기매니홀드","value":5},
{"label":"흡기온도센서","value":5},
{"label":"흡기온도압력센서","value":5},
{"label":"흡입엑추에이터","value":5},
{"label":"하네스와이어링","value":5},
{"label":"하네스","value":5},
{"label":"퓨즈","value":2},
{"label":"휴즈","value":2},
{"label":"밸브스프링 리테이너","value":4},
{"label":"밸브스프링","value":4},
{"label":"밸브스템","value":4},
{"label":"밸브씰","value":4},
{"label":"헤드밸브","value":4},
{"label":"실린더밸브","value":4},
{"label":"믹서","value":5},
{"label":"태핏(tappet)","value":4},
{"label":"밸브가이드","value":4},
{"label":"밸브 로커암","value":4},
{"label":"잠바카바 가스켓","value":2},
{"label":"잠바카바","value":4},
{"label":"로커암 샤프트","value":4},
{"label":"로커암","value":4},
{"label":"로커암 어셈블리","value":4},
{"label":"실린더 보어","value":4},
{"label":"푸쉬로드","value":4},
{"label":"푸시로드","value":4},
{"label":"베이퍼라이저","value":5},
{"label":"햇도","value":4},
{"label":"해또","value":4},
{"label":"기화기","value":5},
{"label":"혼합기","value":5},
{"label":"캠팔로워","value":4},
{"label":"타이밍기어","value":4},
{"label":"타이밍벨트","value":4},
{"label":"냉각수 호수","value":2},
{"label":"냉각수 호스","value":2},
{"label":"냉각수 탱크","value":2},
{"label":"파워보조탱크","value":2},
{"label":"연료분사기","value":5},
{"label":"파워스티어링리저브","value":5},
{"label":"파워오일리저버탱크","value":5},
{"label":"파워오일탱크","value":2},
{"label":"로커암 카바 개스킷 누유","value":2},
{"label":"로커암 카바 개스킷 누유","value":2},
{"label":"로커암 커버 개스킷 누유","value":2},
{"label":"로커암 커버 개스킷 누유","value":2},
{"label":"로커암 카바 개스킷 누유","value":2},
{"label":"로커암 카바 개스킷","value":2},
{"label":"로커암 커버 개스킷 누유","value":2},
{"label":"로커암 커버 개스킷","value":2},
{"label":"로커암 카바 가스겟 누유","value":2},
{"label":"로커암 카바 가스겟 누유","value":2},
{"label":"로커암 커버 가스겟 누유","value":2},
{"label":"로커암 커버 가스겟 누유","value":2},
{"label":"로커암 카바 가스켓 누유","value":2},
{"label":"로커암 카바 가스켓","value":2},
{"label":"로커암 커버 가스켓 누유","value":2},
{"label":"로커암 커버 가스켓","value":2},
{"label":"오일팬 오일누유","value":2},
{"label":"슈라우드(shroud))","value":2},
{"label":"수온조절기","value":5},
{"label":"냉각수펌프","value":5},
{"label":"물펌프","value":5},
{"label":"워터텀퍼레이터센서","value":5},
{"label":"워터펌프","value":5},
{"label":"워터펌프 누수","value":2},
{"label":"타이밍 커버 누유","value":2},
{"label":"드리븐기어","value":4},
{"label":"워터펌프 모터","value":5},
{"label":"CVVT","value":5},
{"label":"서지탱크뚜껑","value":2},
{"label":"냉각수통 캡","value":2},
{"label":"고압연료펌프","value":5},
{"label":"드래인 볼트","value":2},
{"label":"드래인 곡구","value":2},
{"label":"드래인 콕","value":2},
{"label":"드래인 플러그","value":2},
{"label":"드래인코크","value":2},
{"label":"드레인 볼트","value":2},
{"label":"드레인 곡구","value":2},
{"label":"드레인 콕","value":2},
{"label":"드레인 플러그","value":2},
{"label":"드레인코크","value":2},
{"label":"곡구","value":2},
{"label":"코크","value":2},
{"label":"딜리버리 파이프","value":2},
{"label":"모도시호수","value":2},
{"label":"모도시호스","value":2},
{"label":"모도시","value":2},
{"label":"리턴파이프","value":2},
{"label":"리턴호스","value":2},
{"label":"레일압력센서","value":5},
{"label":"텐션베어링","value":2},
{"label":"텐셔너","value":2},
{"label":"마우라","value":2},
{"label":"마후라커터","value":2},
{"label":"마후라팁","value":2},
{"label":"마후라","value":2},
{"label":"머플러팁","value":2},
{"label":"머플러커터","value":2},
{"label":"머플러","value":2},
{"label":"BSM모듈","value":4},
{"label":"밸런스 샤프트 모듈","value":4},
{"label":"점화코일","value":2},
{"label":"캐니스터","value":5},
{"label":"캠샤프트 포지션센서(CMPS/ CPS)","value":5},
{"label":"수온컨트롤 어셈블리","value":5},
{"label":"요소수레벨센서","value":2},
{"label":"셋브레이터","value":5},
{"label":"인젝터 클리닝","value":2},
{"label":"인젝터 크리닝","value":2},
{"label":"클램프","value":2},
{"label":"호스반도(엔진)","value":2},
{"label":"호수반도(엔진)","value":2},
{"label":"호수클램프(엔진)","value":2},
{"label":"호스클램프(엔진)","value":2},
{"label":"퍼지밸브","value":5},
{"label":"밸브커버 가스켓누유","value":2},
{"label":"헤드커버 가스켓누유","value":2},
{"label":"고압케이블","value":2},
{"label":"점화케이블","value":2},
{"label":"방열판","value":2},
{"label":"히트프로텍터","value":2},
{"label":"엑셀레이터 케이블","value":5},
{"label":"엑셀레이터 페달","value":2},
{"label":"가속페달","value":2},
{"label":"엑셀페달","value":2},
{"label":"악셀레이터 케이블","value":5},
{"label":"악셀페달","value":2},
{"label":"악셀레이터 페달","value":2},
{"label":"연료딜리버리모듈","value":5},
{"label":"오일젯","value":4},
{"label":"석션젯펌프","value":4},
{"label":"뜨개","value":5},
{"label":"연료센더","value":5},
{"label":"연료우끼","value":5},
{"label":"오일필러캡","value":2},
{"label":"엔진오일캡","value":2},
{"label":"오일캡","value":2},
{"label":"람다센서","value":2},
{"label":"연료캡","value":2},
{"label":"연료주입캡","value":2},
{"label":"연료필러캡","value":2},
{"label":"스크린히트","value":2},
{"label":"요소수 히팅","value":2},
{"label":"유레아 히팅","value":2},
{"label":"유레아 탱크","value":2},
{"label":"도우징인젝터","value":2},
{"label":"도우징모듈","value":2},
{"label":"도우징분사노즐","value":2},
{"label":"도우징분사펌프","value":2},
{"label":"도징인젝터","value":2},
{"label":"도징모듈","value":2},
{"label":"도징분사노즐","value":2},
{"label":"도징분사펌프","value":2},
{"label":"DCU(도징컨트롤유닛)","value":2},
{"label":"요소수필터","value":2},
{"label":"유레아필터","value":2},
{"label":"요소수센서","value":2},
{"label":"유레아센서","value":2},
{"label":"오일스트레이너","value":4},
{"label":"덕팅(흡기장치)","value":2},
{"label":"에어덕트","value":2},
{"label":"배전기캡","value":2},
{"label":"리후다","value":4},
{"label":"리우다","value":4},
{"label":"뷔우다","value":5},
{"label":"비후다캡","value":2},
{"label":"디스트리뷰터캡","value":2},
{"label":"배전기","value":5},
{"label":"비후다","value":5},
{"label":"디스트리뷰터","value":5},
{"label":"베어링캡","value":4},
{"label":"저널베어링","value":4},
{"label":"메탈베어링","value":4},
{"label":"센터베어링(엔진)","value":4},
{"label":"메달","value":4},
{"label":"크랭크 암","value":4},
{"label":"크랭크 핀","value":4},
{"label":"크랭크 저널","value":4},
{"label":"피스톤 핀","value":4},
{"label":"링구","value":4},
{"label":"피스톤 링","value":4},
{"label":"피스톤","value":4},
{"label":"커넥팅로드핀","value":4},
{"label":"캠","value":4},
{"label":"밸브가이드","value":4},
{"label":"접지터미널","value":5},
{"label":"접지배선","value":5},
{"label":"접지케이블","value":5},
{"label":"가이드씰고무","value":4},
{"label":"써머스타트","value":5},
{"label":"가이드실 고무","value":4},
{"label":"가이드씰","value":4},
{"label":"크랭크샤프트 플랜지","value":4},
{"label":"레더프레임","value":4},
{"label":"흡기압력센서","value":5},
{"label":"투웨이밸브","value":5},
{"label":"2way밸브","value":5},
{"label":"에어플로미터","value":5},
{"label":"인슐레이터","value":5},
{"label":"CVVT 오일온도센서","value":5},
{"label":"CVVT 오일컨트롤 밸브","value":5},
{"label":"DPF","value":2},
{"label":"DPF차압센서","value":2},
{"label":"EGR 밸브","value":5},
{"label":"EGR 솔레노이드 밸브","value":5},
{"label":"EGR 쿨러","value":5},
{"label":"배기가스재순환계통감시장치","value":5},
{"label":"바이패스","value":5},
{"label":"EGR 쿨러 바이패스 솔레노이드 밸브","value":5},
{"label":"ETC(electronic throttle control) 시스템","value":5},
{"label":"HCU(hybrid control unit)","value":2},
{"label":"ISG OFF 스위치","value":2},
{"label":"LPI 연료펌프","value":5},
{"label":"PM센서","value":2},
{"label":"낙스센서","value":2},
{"label":"녹스센서","value":2},
{"label":"Nox센서","value":2},
{"label":"스파크플러그","value":2},
{"label":"이리듐플러그","value":2},
{"label":"백금플러그","value":2},
{"label":"점화플러그","value":2},
{"label":"RPM센서","value":5},
{"label":"가열플러그","value":2},
{"label":"글로플러그","value":2},
{"label":"글로우플러그","value":2},
{"label":"예열플러그","value":2},
{"label":"글로우 릴레이","value":5},
{"label":"글로우 릴레이 유닛","value":5},
{"label":"글로우 컨트롤 유닛","value":5},
{"label":"써머밸브","value":5},
{"label":"냉각팬 모터","value":5},
{"label":"서머밸브","value":5},
{"label":"냉각수온센서","value":5},
{"label":"노크센서","value":5},
{"label":"대기온도 센서","value":5},
{"label":"대기압측정센서","value":5},
{"label":"VGT 컨트롤 솔레노이드밸브","value":5},
{"label":"가변스웰엑추에이터","value":5},
{"label":"가변흡기솔레노이드밸브","value":5},
{"label":"공기량 측정센서(MAFS)","value":5},
{"label":"서브엔진","value":4},
{"label":"쇼트엔진","value":4},
{"label":"도징모듈","value":2},
{"label":"도징컨트롤유닛","value":2},
{"label":"파워 스티어링 펌프","value":5},
{"label":"배기매니폴드 개스킷","value":2},
{"label":"배기매니홀드 개스킷","value":2},
{"label":"배기매니폴드 가스켓","value":2},
{"label":"배기매니홀드 가스켓","value":2},
{"label":"배기매니폴드","value":5},
{"label":"파워스티어링 오일펌프","value":5},
{"label":"파워 펌프","value":5},
{"label":"벨트 텐셔너","value":2},
{"label":"아이들 베어링","value":2},
{"label":"라디에이터","value":5},
{"label":"라지에이터","value":5},
{"label":"배기메니홀드","value":5},
{"label":"이그저스트 매니홀드","value":5},
{"label":"배기가스 온도센서","value":2},
{"label":"지르코니아센서","value":2},
{"label":"산소센서","value":2},
{"label":"섬머스텟 하우징","value":5},
{"label":"썸머스텟 하우징","value":5},
{"label":"썸모스텟 하우징","value":5},
{"label":"서머스탯 하우징","value":5},
{"label":"서모스탯 하우징","value":5},
{"label":"서모스텟 하우징","value":5},
{"label":"서머스텟","value":5},
{"label":"서머스텟 하우징","value":5},
{"label":"서플라이모듈","value":2},
{"label":"수온컨트롤 어셈블리","value":5},
{"label":"스로틀플랩컨트롤솔레노이드밸브","value":5},
{"label":"스타트모터","value":6},
{"label":"스타트모다","value":6},
{"label":"스타트","value":6},
{"label":"스타터","value":6},
{"label":"스타터모터","value":6},
{"label":"스타트 릴레이","value":5},
{"label":"실린더블럭","value":4},
{"label":"실린더해드","value":4},
{"label":"실린더해드커버","value":4},
{"label":"실린더헤드","value":4},
{"label":"실린더헤드커버","value":4},
{"label":"아이들러","value":2},
{"label":"알터네이터","value":6},
{"label":"AC제너레이터","value":6},
{"label":"제네레이터","value":6},
{"label":"제네레다","value":6},
{"label":"AC발전기","value":6},
{"label":"교류발전기","value":6},
{"label":"발전기","value":6},
{"label":"기동전동기","value":6},
{"label":"시동모터","value":6},
{"label":"전자제어유닛(ECU)","value":5},
{"label":"에어컨트롤밸브(스로틀)","value":5},
{"label":"액체봉입식 마운트","value":2},
{"label":"엔진마운팅(미미)","value":2},
{"label":"엔진오일","value":2},
{"label":"엔진커버","value":2},
{"label":"엔진컨트롤모듈(ECU)","value":5}
]